const actions = {
  SET_STATE: 'profil/SET_STATE',
  UPDATE_BACKGROUND_INFO: 'profil/UPDATE_BACKGROUND_INFO',
  GET_NOTIFICATION_CONFIGS: 'profil/GET_NOTIFICATION_CONFIGS',
  UPDATE_NOTIFICATION_CONFIGS: 'profil/UPDATE_NOTIFICATION_CONFIGS',
  REMOVE_ACCOUNT: 'profil/REMOVE_ACCOUNT',
}

export default actions
